/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteIndexRouteImport } from './routes/invite/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DashboardSpaceSlugRouteRouteImport } from './routes/dashboard/space/$slug/route'
import { Route as DashboardLabSlugRouteRouteImport } from './routes/dashboard/lab/$slug/route'
import { Route as DashboardSpaceSlugIndexRouteImport } from './routes/dashboard/space/$slug/index'
import { Route as DashboardLabSlugIndexRouteImport } from './routes/dashboard/lab/$slug/index'
import { Route as DashboardSpaceSlugTeamIndexRouteImport } from './routes/dashboard/space/$slug/team/index'
import { Route as DashboardSpaceSlugGeneralIndexRouteImport } from './routes/dashboard/space/$slug/general/index'
import { Route as DashboardSpaceSlugBillingIndexRouteImport } from './routes/dashboard/space/$slug/billing/index'
import { Route as DashboardLabSlugSettingsIndexRouteImport } from './routes/dashboard/lab/$slug/settings/index'
import { Route as DashboardLabSlugCanvasIndexRouteImport } from './routes/dashboard/lab/$slug/canvas/index'
import { Route as DashboardLabSlugAskIndexRouteImport } from './routes/dashboard/lab/$slug/ask/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteIndexRoute = InviteIndexRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardSpaceSlugRouteRoute = DashboardSpaceSlugRouteRouteImport.update({
  id: '/space/$slug',
  path: '/space/$slug',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLabSlugRouteRoute = DashboardLabSlugRouteRouteImport.update({
  id: '/lab/$slug',
  path: '/lab/$slug',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSpaceSlugIndexRoute = DashboardSpaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSpaceSlugRouteRoute,
} as any)
const DashboardLabSlugIndexRoute = DashboardLabSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLabSlugRouteRoute,
} as any)
const DashboardSpaceSlugTeamIndexRoute =
  DashboardSpaceSlugTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => DashboardSpaceSlugRouteRoute,
  } as any)
const DashboardSpaceSlugGeneralIndexRoute =
  DashboardSpaceSlugGeneralIndexRouteImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => DashboardSpaceSlugRouteRoute,
  } as any)
const DashboardSpaceSlugBillingIndexRoute =
  DashboardSpaceSlugBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => DashboardSpaceSlugRouteRoute,
  } as any)
const DashboardLabSlugSettingsIndexRoute =
  DashboardLabSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardLabSlugRouteRoute,
  } as any)
const DashboardLabSlugCanvasIndexRoute =
  DashboardLabSlugCanvasIndexRouteImport.update({
    id: '/canvas/',
    path: '/canvas/',
    getParentRoute: () => DashboardLabSlugRouteRoute,
  } as any)
const DashboardLabSlugAskIndexRoute =
  DashboardLabSlugAskIndexRouteImport.update({
    id: '/ask/',
    path: '/ask/',
    getParentRoute: () => DashboardLabSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/invite': typeof InviteIndexRoute
  '/dashboard/lab/$slug': typeof DashboardLabSlugRouteRouteWithChildren
  '/dashboard/space/$slug': typeof DashboardSpaceSlugRouteRouteWithChildren
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/dashboard/lab/$slug/': typeof DashboardLabSlugIndexRoute
  '/dashboard/space/$slug/': typeof DashboardSpaceSlugIndexRoute
  '/dashboard/lab/$slug/ask': typeof DashboardLabSlugAskIndexRoute
  '/dashboard/lab/$slug/canvas': typeof DashboardLabSlugCanvasIndexRoute
  '/dashboard/lab/$slug/settings': typeof DashboardLabSlugSettingsIndexRoute
  '/dashboard/space/$slug/billing': typeof DashboardSpaceSlugBillingIndexRoute
  '/dashboard/space/$slug/general': typeof DashboardSpaceSlugGeneralIndexRoute
  '/dashboard/space/$slug/team': typeof DashboardSpaceSlugTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/invite': typeof InviteIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/dashboard/lab/$slug': typeof DashboardLabSlugIndexRoute
  '/dashboard/space/$slug': typeof DashboardSpaceSlugIndexRoute
  '/dashboard/lab/$slug/ask': typeof DashboardLabSlugAskIndexRoute
  '/dashboard/lab/$slug/canvas': typeof DashboardLabSlugCanvasIndexRoute
  '/dashboard/lab/$slug/settings': typeof DashboardLabSlugSettingsIndexRoute
  '/dashboard/space/$slug/billing': typeof DashboardSpaceSlugBillingIndexRoute
  '/dashboard/space/$slug/general': typeof DashboardSpaceSlugGeneralIndexRoute
  '/dashboard/space/$slug/team': typeof DashboardSpaceSlugTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/invite/': typeof InviteIndexRoute
  '/dashboard/lab/$slug': typeof DashboardLabSlugRouteRouteWithChildren
  '/dashboard/space/$slug': typeof DashboardSpaceSlugRouteRouteWithChildren
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/dashboard/lab/$slug/': typeof DashboardLabSlugIndexRoute
  '/dashboard/space/$slug/': typeof DashboardSpaceSlugIndexRoute
  '/dashboard/lab/$slug/ask/': typeof DashboardLabSlugAskIndexRoute
  '/dashboard/lab/$slug/canvas/': typeof DashboardLabSlugCanvasIndexRoute
  '/dashboard/lab/$slug/settings/': typeof DashboardLabSlugSettingsIndexRoute
  '/dashboard/space/$slug/billing/': typeof DashboardSpaceSlugBillingIndexRoute
  '/dashboard/space/$slug/general/': typeof DashboardSpaceSlugGeneralIndexRoute
  '/dashboard/space/$slug/team/': typeof DashboardSpaceSlugTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/'
    | '/invite'
    | '/dashboard/lab/$slug'
    | '/dashboard/space/$slug'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/lab/$slug/'
    | '/dashboard/space/$slug/'
    | '/dashboard/lab/$slug/ask'
    | '/dashboard/lab/$slug/canvas'
    | '/dashboard/lab/$slug/settings'
    | '/dashboard/space/$slug/billing'
    | '/dashboard/space/$slug/general'
    | '/dashboard/space/$slug/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/invite'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/lab/$slug'
    | '/dashboard/space/$slug'
    | '/dashboard/lab/$slug/ask'
    | '/dashboard/lab/$slug/canvas'
    | '/dashboard/lab/$slug/settings'
    | '/dashboard/space/$slug/billing'
    | '/dashboard/space/$slug/general'
    | '/dashboard/space/$slug/team'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/'
    | '/invite/'
    | '/dashboard/lab/$slug'
    | '/dashboard/space/$slug'
    | '/auth/login/'
    | '/auth/register/'
    | '/dashboard/lab/$slug/'
    | '/dashboard/space/$slug/'
    | '/dashboard/lab/$slug/ask/'
    | '/dashboard/lab/$slug/canvas/'
    | '/dashboard/lab/$slug/settings/'
    | '/dashboard/space/$slug/billing/'
    | '/dashboard/space/$slug/general/'
    | '/dashboard/space/$slug/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  InviteIndexRoute: typeof InviteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/': {
      id: '/invite/'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/space/$slug': {
      id: '/dashboard/space/$slug'
      path: '/space/$slug'
      fullPath: '/dashboard/space/$slug'
      preLoaderRoute: typeof DashboardSpaceSlugRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/lab/$slug': {
      id: '/dashboard/lab/$slug'
      path: '/lab/$slug'
      fullPath: '/dashboard/lab/$slug'
      preLoaderRoute: typeof DashboardLabSlugRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/space/$slug/': {
      id: '/dashboard/space/$slug/'
      path: '/'
      fullPath: '/dashboard/space/$slug/'
      preLoaderRoute: typeof DashboardSpaceSlugIndexRouteImport
      parentRoute: typeof DashboardSpaceSlugRouteRoute
    }
    '/dashboard/lab/$slug/': {
      id: '/dashboard/lab/$slug/'
      path: '/'
      fullPath: '/dashboard/lab/$slug/'
      preLoaderRoute: typeof DashboardLabSlugIndexRouteImport
      parentRoute: typeof DashboardLabSlugRouteRoute
    }
    '/dashboard/space/$slug/team/': {
      id: '/dashboard/space/$slug/team/'
      path: '/team'
      fullPath: '/dashboard/space/$slug/team'
      preLoaderRoute: typeof DashboardSpaceSlugTeamIndexRouteImport
      parentRoute: typeof DashboardSpaceSlugRouteRoute
    }
    '/dashboard/space/$slug/general/': {
      id: '/dashboard/space/$slug/general/'
      path: '/general'
      fullPath: '/dashboard/space/$slug/general'
      preLoaderRoute: typeof DashboardSpaceSlugGeneralIndexRouteImport
      parentRoute: typeof DashboardSpaceSlugRouteRoute
    }
    '/dashboard/space/$slug/billing/': {
      id: '/dashboard/space/$slug/billing/'
      path: '/billing'
      fullPath: '/dashboard/space/$slug/billing'
      preLoaderRoute: typeof DashboardSpaceSlugBillingIndexRouteImport
      parentRoute: typeof DashboardSpaceSlugRouteRoute
    }
    '/dashboard/lab/$slug/settings/': {
      id: '/dashboard/lab/$slug/settings/'
      path: '/settings'
      fullPath: '/dashboard/lab/$slug/settings'
      preLoaderRoute: typeof DashboardLabSlugSettingsIndexRouteImport
      parentRoute: typeof DashboardLabSlugRouteRoute
    }
    '/dashboard/lab/$slug/canvas/': {
      id: '/dashboard/lab/$slug/canvas/'
      path: '/canvas'
      fullPath: '/dashboard/lab/$slug/canvas'
      preLoaderRoute: typeof DashboardLabSlugCanvasIndexRouteImport
      parentRoute: typeof DashboardLabSlugRouteRoute
    }
    '/dashboard/lab/$slug/ask/': {
      id: '/dashboard/lab/$slug/ask/'
      path: '/ask'
      fullPath: '/dashboard/lab/$slug/ask'
      preLoaderRoute: typeof DashboardLabSlugAskIndexRouteImport
      parentRoute: typeof DashboardLabSlugRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardLabSlugRouteRouteChildren {
  DashboardLabSlugIndexRoute: typeof DashboardLabSlugIndexRoute
  DashboardLabSlugAskIndexRoute: typeof DashboardLabSlugAskIndexRoute
  DashboardLabSlugCanvasIndexRoute: typeof DashboardLabSlugCanvasIndexRoute
  DashboardLabSlugSettingsIndexRoute: typeof DashboardLabSlugSettingsIndexRoute
}

const DashboardLabSlugRouteRouteChildren: DashboardLabSlugRouteRouteChildren = {
  DashboardLabSlugIndexRoute: DashboardLabSlugIndexRoute,
  DashboardLabSlugAskIndexRoute: DashboardLabSlugAskIndexRoute,
  DashboardLabSlugCanvasIndexRoute: DashboardLabSlugCanvasIndexRoute,
  DashboardLabSlugSettingsIndexRoute: DashboardLabSlugSettingsIndexRoute,
}

const DashboardLabSlugRouteRouteWithChildren =
  DashboardLabSlugRouteRoute._addFileChildren(
    DashboardLabSlugRouteRouteChildren,
  )

interface DashboardSpaceSlugRouteRouteChildren {
  DashboardSpaceSlugIndexRoute: typeof DashboardSpaceSlugIndexRoute
  DashboardSpaceSlugBillingIndexRoute: typeof DashboardSpaceSlugBillingIndexRoute
  DashboardSpaceSlugGeneralIndexRoute: typeof DashboardSpaceSlugGeneralIndexRoute
  DashboardSpaceSlugTeamIndexRoute: typeof DashboardSpaceSlugTeamIndexRoute
}

const DashboardSpaceSlugRouteRouteChildren: DashboardSpaceSlugRouteRouteChildren =
  {
    DashboardSpaceSlugIndexRoute: DashboardSpaceSlugIndexRoute,
    DashboardSpaceSlugBillingIndexRoute: DashboardSpaceSlugBillingIndexRoute,
    DashboardSpaceSlugGeneralIndexRoute: DashboardSpaceSlugGeneralIndexRoute,
    DashboardSpaceSlugTeamIndexRoute: DashboardSpaceSlugTeamIndexRoute,
  }

const DashboardSpaceSlugRouteRouteWithChildren =
  DashboardSpaceSlugRouteRoute._addFileChildren(
    DashboardSpaceSlugRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLabSlugRouteRoute: typeof DashboardLabSlugRouteRouteWithChildren
  DashboardSpaceSlugRouteRoute: typeof DashboardSpaceSlugRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLabSlugRouteRoute: DashboardLabSlugRouteRouteWithChildren,
  DashboardSpaceSlugRouteRoute: DashboardSpaceSlugRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  InviteIndexRoute: InviteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
