/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DashboardLabIdRouteRouteImport } from './routes/dashboard/lab/$id/route'
import { Route as DashboardLabIdIndexRouteImport } from './routes/dashboard/lab/$id/index'
import { Route as DashboardLabIdCanvasIndexRouteImport } from './routes/dashboard/lab/$id/canvas/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardLabIdRouteRoute = DashboardLabIdRouteRouteImport.update({
  id: '/lab/$id',
  path: '/lab/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLabIdIndexRoute = DashboardLabIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLabIdRouteRoute,
} as any)
const DashboardLabIdCanvasIndexRoute =
  DashboardLabIdCanvasIndexRouteImport.update({
    id: '/canvas/',
    path: '/canvas/',
    getParentRoute: () => DashboardLabIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/lab/$id': typeof DashboardLabIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/dashboard/lab/$id/': typeof DashboardLabIdIndexRoute
  '/dashboard/lab/$id/canvas': typeof DashboardLabIdCanvasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/dashboard/lab/$id': typeof DashboardLabIdIndexRoute
  '/dashboard/lab/$id/canvas': typeof DashboardLabIdCanvasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/lab/$id': typeof DashboardLabIdRouteRouteWithChildren
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/dashboard/lab/$id/': typeof DashboardLabIdIndexRoute
  '/dashboard/lab/$id/canvas/': typeof DashboardLabIdCanvasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/lab/$id'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/lab/$id/'
    | '/dashboard/lab/$id/canvas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/lab/$id'
    | '/dashboard/lab/$id/canvas'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/lab/$id'
    | '/auth/login/'
    | '/auth/register/'
    | '/dashboard/lab/$id/'
    | '/dashboard/lab/$id/canvas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/lab/$id': {
      id: '/dashboard/lab/$id'
      path: '/lab/$id'
      fullPath: '/dashboard/lab/$id'
      preLoaderRoute: typeof DashboardLabIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/lab/$id/': {
      id: '/dashboard/lab/$id/'
      path: '/'
      fullPath: '/dashboard/lab/$id/'
      preLoaderRoute: typeof DashboardLabIdIndexRouteImport
      parentRoute: typeof DashboardLabIdRouteRoute
    }
    '/dashboard/lab/$id/canvas/': {
      id: '/dashboard/lab/$id/canvas/'
      path: '/canvas'
      fullPath: '/dashboard/lab/$id/canvas'
      preLoaderRoute: typeof DashboardLabIdCanvasIndexRouteImport
      parentRoute: typeof DashboardLabIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardLabIdRouteRouteChildren {
  DashboardLabIdIndexRoute: typeof DashboardLabIdIndexRoute
  DashboardLabIdCanvasIndexRoute: typeof DashboardLabIdCanvasIndexRoute
}

const DashboardLabIdRouteRouteChildren: DashboardLabIdRouteRouteChildren = {
  DashboardLabIdIndexRoute: DashboardLabIdIndexRoute,
  DashboardLabIdCanvasIndexRoute: DashboardLabIdCanvasIndexRoute,
}

const DashboardLabIdRouteRouteWithChildren =
  DashboardLabIdRouteRoute._addFileChildren(DashboardLabIdRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLabIdRouteRoute: typeof DashboardLabIdRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLabIdRouteRoute: DashboardLabIdRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
