export const BillingList = [
  {
    plan: "free",
    planLabel: "Free Plan",
    planStatus: "Current",
    price: "$0",
    ctaLabel: null,
    buttonType: "outline",
    features: [
      "1 Free Workspace Only",
      "3 Free Labs Only",
      "Limited whiteboard Features",
      "Limited Lab Storage",
      "Limited AI Querying",
    ],
    endingPara:
      "Try our freemium plan to explore our application. Upgrade to Pro or Enterprise for more advanced features and support.",
  },
  {
    plan: "pro",
    planLabel: "Pro Plan",
    planStatus: "Popular",
    price: "$29",
    ctaLabel: "Upgrade to Pro",
    buttonType: "default",
    features: [
      "Up to 3 Workspaces",
      "5 Labs per Workspace",
      "All Whiteboard Features",
      "Advanced Analytics",
      "Collaborate with Others",
      "Improve Lab Storage",
      "Better AI Querying",
    ],
    endingPara:
      "Try our Pro plan to explore all features. Upgrade to Enterprise for more advanced features and support.",
  },
  {
    plan: "enterprise",
    planLabel: "Enterprise Plan",
    planStatus: "Beast",
    price: "$99",
    ctaLabel: "Upgrade to Enterprise",
    buttonType: "secondary",
    features: [
      "Unlimited Workspaces",
      "Unlimited Labs per Workspace",
      "All Whiteboard Features",
      "Advanced Analytics",
      "Collaborate with Others",
      "Unlimited Lab Storage",
      "Unlimited AI Querying",
      "Priority Support",
      "External Integrations",
      "Dedicated Account Manager",
    ],
    endingPara:
      "Try our Enterprise plan to explore all features. Contact us for more information on custom solutions and support.",
  },
];
