version: "3.8"

services:
  db:
    image: postgres:15
    container_name: lumini-db
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: abc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma
    environment:
      - IS_PERSISTENT=TRUE

volumes:
  postgres_data:
  chroma_data:
